### ISSUE TITLE
Bluetooth socket instantly closes after connecting with success

### ISSUE THREAD

**Issue by Aymeric-H** [pwittchen/neurosky-android-sdk#86]
Hello I'm currently using the official ThinkGear SDK from NeuroSky with mindwave mobile 2 and and I'm getting bluetooth connection issues. The device connects to the software but then it gets instantly disconnected. I checked on to the logs and saw that bluetooth socket was closed by close() method. I tried to discover why this issue is happening each time I try to connect the device but I'm running out of ideas. Since you worked and seem to know the SDK pretty well do you have any idea what could cause this issue ?

**Comment by pwittchen** [comment]
Hi,

Can you provide more details? E.g. exact steps to reproduce this problem, stacktrace or any code snippet? I guess you are using SDK incorrectly or there are issues with your hardware (phone/tablet or headset). Have you tried my SDK? Have you had the same issues with it? It uses ThinkGear SDK under the hood too, but exposed API looks different.

Regards,
Piotr

**Comment by pwittchen** [comment]
There was no further response, so I'm closing this one.
